# Generated by Django 4.2.10 on 2026-03-28 19:27

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(help_text='Home team short name e.g. MI', max_length=100)),
                ('team_b', models.CharField(help_text='Away team short name e.g. CSK', max_length=100)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('match_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='SCHEDULED', max_length=10)),
                ('external_id', models.CharField(blank=True, help_text='ID from cricket data API (Cricbuzz / RapidAPI)', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-match_date'],
                'indexes': [models.Index(fields=['status'], name='idx_matches_status'), models.Index(fields=['match_date'], name='idx_matches_date')],
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=10)),
                ('max_participants', models.PositiveIntegerField(default=100)),
                ('entry_fee_eth', models.DecimalField(decimal_places=8, default=Decimal('0.003'), help_text='Entry fee in ETH (default 0.003)', max_digits=18)),
                ('prize_pool_eth', models.DecimalField(decimal_places=8, default=0, help_text='Accumulated from entries (auto-updated)', max_digits=18)),
                ('network', models.CharField(default='base-sepolia', help_text='Blockchain network identifier', max_length=50)),
                ('chain_id', models.PositiveIntegerField(default=84532, help_text='EVM chain ID (Base Sepolia = 84532)')),
                ('contract_contest_id', models.PositiveIntegerField(blank=True, help_text='Solidity contest ID on-chain', null=True)),
                ('tx_hash_created', models.CharField(blank=True, help_text='Tx hash from createContest() call', max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='contests.match')),
            ],
            options={
                'db_table': 'contests',
            },
        ),
        migrations.CreateModel(
            name='AdminEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_eth', models.DecimalField(decimal_places=8, help_text='ETH collected as platform fee', max_digits=18)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('5.0'), help_text='Fee % taken (default 5.0)', max_digits=5)),
                ('tx_hash', models.CharField(blank=True, help_text='On-chain tx hash for fee transfer to owner', max_length=66)),
                ('recipient_wallet', models.CharField(blank=True, help_text='Owner wallet that received the fee', max_length=42)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_earnings', to='contests.contest')),
            ],
            options={
                'verbose_name': 'Admin Earnings',
                'db_table': 'admin_earnings',
            },
        ),
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_players', models.JSONField(help_text='List of 11 player IDs selected by the user')),
                ('captain_id', models.PositiveIntegerField(help_text='Player ID designated as captain')),
                ('vice_captain_id', models.PositiveIntegerField(help_text='Player ID designated as vice-captain')),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('tx_hash', models.CharField(blank=True, help_text='On-chain tx hash for the entry fee payment', max_length=66)),
                ('prize_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teams', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_entries',
                'indexes': [models.Index(fields=['contest', 'user'], name='idx_entries_contest_user'), models.Index(fields=['contest', 'rank'], name='idx_entries_contest_rank')],
                'unique_together': {('contest', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PrizeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text='1 = winner, 2 = runner-up, etc.')),
                ('prize_eth', models.DecimalField(decimal_places=8, help_text='ETH amount distributed to this user', max_digits=18)),
                ('tx_hash', models.CharField(blank=True, help_text='On-chain tx hash for the prize transfer', max_length=66)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_distributions', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prize Distribution',
                'db_table': 'prize_distributions',
                'ordering': ['rank'],
                'unique_together': {('contest', 'rank')},
            },
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['status'], name='idx_contests_status'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['match', 'status'], name='idx_contests_match_status'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['contract_contest_id'], name='idx_contests_contract_id'),
        ),
    ]
