# Generated by Django 4.2.10 on 2026-03-28 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.DecimalField(decimal_places=2, default=0, help_text="Sum of selected players' fantasy points (captain 2x, vc 1.5x)", max_digits=10)),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Final leaderboard rank within this contest', null=True)),
                ('tx_hash', models.CharField(blank=True, help_text='Tx hash of the joinContest() call on Base Sepolia', max_length=66)),
                ('prize_claimed', models.BooleanField(default=False, help_text='True once prize ETH has been transferred on-chain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_user_teams', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_teams',
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.PositiveIntegerField(default=0)),
                ('balls_faced', models.PositiveIntegerField(default=0)),
                ('fours', models.PositiveIntegerField(default=0)),
                ('sixes', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('overs', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('catches', models.PositiveIntegerField(default=0)),
                ('stumpings', models.PositiveIntegerField(default=0)),
                ('fantasy_points', models.DecimalField(decimal_places=2, default=0, help_text='Calculated fantasy points for this performance', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scores', to='contests.contest')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='players.player')),
            ],
            options={
                'db_table': 'player_scores',
            },
        ),
        migrations.CreateModel(
            name='UserTeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_captain', models.BooleanField(default=False)),
                ('is_vice_captain', models.BooleanField(default=False)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, help_text='Base fantasy points × multiplier (2x captain / 1.5x vc)', max_digits=8)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_selections', to='players.player')),
                ('user_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='scores.userteam')),
            ],
            options={
                'db_table': 'user_team_players',
                'indexes': [models.Index(fields=['user_team'], name='idx_utplayer_team'), models.Index(fields=['player'], name='idx_utplayer_player')],
                'unique_together': {('user_team', 'player')},
            },
        ),
        migrations.AddIndex(
            model_name='userteam',
            index=models.Index(fields=['contest', 'total_points'], name='idx_userteam_leaderboard'),
        ),
        migrations.AddIndex(
            model_name='userteam',
            index=models.Index(fields=['tx_hash'], name='idx_userteam_txhash'),
        ),
        migrations.AlterUniqueTogether(
            name='userteam',
            unique_together={('user', 'contest')},
        ),
        migrations.AddIndex(
            model_name='playerscore',
            index=models.Index(fields=['contest', 'fantasy_points'], name='idx_scores_contest_pts'),
        ),
        migrations.AlterUniqueTogether(
            name='playerscore',
            unique_together={('player', 'contest')},
        ),
    ]
