# Generated by Django 4.2.10 on 2026-03-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPLTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('home_city', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IPL Team',
                'verbose_name_plural': 'IPL Teams',
                'db_table': 'ipl_teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('BAT', 'Batsman'), ('BWL', 'Bowler'), ('AR', 'All-Rounder'), ('WK', 'Wicket-Keeper')], max_length=3)),
                ('credit_value', models.DecimalField(decimal_places=1, default=8.0, help_text='Fantasy credit cost (e.g. 9.5)', max_digits=4)),
                ('is_playing', models.BooleanField(default=True, help_text='True if in playing XI for current match')),
                ('image_url', models.URLField(blank=True)),
                ('ipl_id', models.CharField(blank=True, help_text='External cricket API player ID', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='players.iplteam')),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('is_out', models.BooleanField(default=False)),
                ('overs_bowled', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('wickets', models.IntegerField(default=0)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('maidens', models.IntegerField(default=0)),
                ('no_balls', models.IntegerField(default=0)),
                ('wides', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('stumpings', models.IntegerField(default=0)),
                ('run_outs', models.IntegerField(default=0)),
                ('fantasy_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='contests.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='players.player')),
            ],
            options={
                'verbose_name': 'Player Match Stats',
                'db_table': 'player_match_stats',
                'unique_together': {('player', 'match')},
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team', 'role'], name='idx_players_team_role'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_playing'], name='idx_players_playing'),
        ),
    ]
